# MIT / Apache-2.0 https://github.com/crates-pro/crates-pro-infra/tree/main/third-party/fixups
cargo_env = true
[[buildscript]]
[buildscript.rustc_flags]
env = { OPENSSL_LIB_DIR = "/usr/local/lib64", OPENSSL_INCLUDE_DIR = "/usr/include", OPT_LEVEL = "3" }
